### ISSUE TITLE
learn.co is broken???

### ISSUE THREAD

**Issue by wtk34500000** [learn-co-curriculum/javascript-objects#36]
what is this?????

1)objects "before all" hook:
error: cannot find module 'jsdom/lib/old-api' 

please help!!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @wtk34500000.

We have updated the materials and believe your issue to have been resolved. In order to access the updated version of this repository, delete your personal fork of the repo via GitHub and then revisit the lesson on learn.co. If learn.co does not see that you have a personal fork on your GitHub account, it will re-fork and provide you the up-to-date lesson.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue.
