### ISSUE TITLE
Cannot find module 'jsdom/lib/old-api

### ISSUE THREAD

**Issue by marinus22** [learn-co-curriculum/javascript-objects#37]
This happens every time I run a test:

![image](https://user-images.githubusercontent.com/40560626/42220786-54342d34-7ed0-11e8-8da0-e14ce99e2242.png)

I've successfully passed other tests and labs, but this happens every few labs.

**Comment by ymohsin-github** [comment]
I also experienced this problem. I was able to find a solution reading through questions other people have asked technical coaches.

Try this:
1. Open the file `package.json` 
2. Find the following piece of code:
`"mocha-jsdom": "^1.1.0"`
3. Replace it with the following piece of code
`"mocha-jsdom": "2.0.0"`
4. Save the file `package.json`
5. Enter the following in the terminal:
`npm install`
6. Now run `learn test` in the terminal to see if the problem is resolved

**Comment by cnezames** [comment]
The above didn't work for me, but it was very similar:

Part 3, instead of what you suggested, I entered:
`mocha-jsdom: "~1.1.0`

Followed the rest of the steps and it worked.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @marinus22.

We have updated the materials and believe your issue to have been resolved. In order to access the updated version of this repository, delete your personal fork of the repo via GitHub and then revisit the lesson on learn.co. If learn.co does not see that you have a personal fork on your GitHub account, it will re-fork and provide you the up-to-date lesson.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
