### ISSUE TITLE
`learn test` not working as expected

### ISSUE THREAD

**Issue by bwitka** [learn-co-curriculum/javascript-objects#38]
Hello Learn.co, 

Below I have included what I got when I tried to run my tests for this lesson with the `learn test` command in my terminal. I searched your Q&A database as well as Google but this seems to be something above my level of comprehension. I hope I am not wasting your time and that this is a legit bug.

Please let me know if you need more info regarding this issue.

Thanks for all you do!

Best,
Beau

// ♥ learn test

> javascript-objects@0.1.0 test /home/bwitka/javascript-objects-bootcamp-prep-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 0   __,------,
 1   __|  /\_/\
 0   _~|_( x .x)
     _ ""  ""

  0 passing (22ms)
  1 failing

  1) objects "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

npm ERR! Test failed.  See above for more details.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @bwitka.

We have updated the materials and believe your issue to have been resolved. In order to access the updated version of this repository, delete your personal fork of the repo via GitHub and then revisit the lesson on learn.co. If learn.co does not see that you have a personal fork on your GitHub account, it will re-fork and provide you the up-to-date lesson.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
