### ISSUE TITLE
Cannot "Submit Pull Request" after completing tests

### ISSUE THREAD

**Issue by BaronLip** [learn-co-curriculum/javascript-objects#44]
After passing tests and "learn submit" through the terminal, I'm unable to move forward by clicking "Submit Pull Request" on the right-side menu. 

![Submit Pull Request issue](https://user-images.githubusercontent.com/45054120/56935770-eb8e2980-6ab8-11e9-8c1a-2c937fff4b89.png)

**Comment by maxwellbenton** [comment]
Hi @BaronLip,

Sorry to hear that you were experiencing problems with Learn. This issue is due to a bug in Learn, and our engineering team has been notified. If you continue to experience this issue on future lessons, please feel free to reach out to support@learn.co for further assistance.

Thank you!
